'use strict';
// MPoint: glossario preimpostato delle sigle piu' comuni nei documenti per la pubblica amministrazione e nei progetti
// del team. Serve quando il documento usa una sigla senza spiegarla: il significato si propone, poi il glossario del
// progetto (scritto a mano) ha sempre la precedenza. Le voci con lettere minuscole (PagoPA, AppIO) si cercano
// cosi' come sono scritte.
const GLOSSARIO_PA = {
  AQ: 'Accordo Quadro',
  SAC: 'Servizi Applicativi in ottica Cloud (accordo quadro Consip)',
  CONSIP: 'Centrale acquisti della pubblica amministrazione',
  PMO: 'Project Management Office',
  PM: 'Project Manager',
  SAL: 'Stato Avanzamento Lavori',
  RUP: 'Responsabile Unico del Procedimento',
  DEC: 'Direttore dell\'Esecuzione del Contratto',
  CE: 'Contratto Esecutivo',
  PdL: 'Piano di Lavoro',
  PDL: 'Piano di Lavoro',
  POP: 'Piano Operativo di Progetto',
  KPI: 'Key Performance Indicator (indicatore di prestazione)',
  SLA: 'Service Level Agreement (livello di servizio)',
  FTE: 'Full Time Equivalent (una persona a tempo pieno)',
  GG: 'Giorni (giornate persona)',
  SPID: 'Sistema Pubblico di Identità Digitale',
  CIE: 'Carta d\'Identità Elettronica',
  CNS: 'Carta Nazionale dei Servizi',
  PagoPA: 'Piattaforma nazionale dei pagamenti verso la pubblica amministrazione',
  PAGOPA: 'Piattaforma nazionale dei pagamenti verso la pubblica amministrazione',
  AppIO: 'App IO, l\'app dei servizi pubblici',
  APPIO: 'App IO, l\'app dei servizi pubblici',
  IO: 'App IO, l\'app dei servizi pubblici',
  PDND: 'Piattaforma Digitale Nazionale Dati (interoperabilità)',
  SEND: 'Servizio Notifiche Digitali (notifiche a valore legale)',
  ANPR: 'Anagrafe Nazionale della Popolazione Residente',
  PNRR: 'Piano Nazionale di Ripresa e Resilienza',
  FESR: 'Fondo Europeo di Sviluppo Regionale',
  FSE: 'Fondo Sociale Europeo',
  FEASR: 'Fondo Europeo Agricolo per lo Sviluppo Rurale',
  PR: 'Programma Regionale',
  PSR: 'Programma di Sviluppo Rurale',
  PSP: 'Piano Strategico della PAC',
  PAC: 'Politica Agricola Comune',
  PA: 'Pubblica Amministrazione',
  TIC: 'Tecnologie dell\'Informazione e della Comunicazione',
  ICT: 'Information and Communication Technology',
  IAM: 'Identity and Access Management (gestione di identità e accessi)',
  API: 'Application Programming Interface (interfaccia tra programmi)',
  DSS: 'Decision Support System (sistema di supporto alle decisioni)',
  OMS: 'Order Management System (gestione degli ordini)',
  CRM: 'Customer Relationship Management',
  ERP: 'Enterprise Resource Planning (gestionale)',
  BI: 'Business Intelligence',
  BPB: 'Business Process Breakdown (mappa dei processi)',
  BPMN: 'Business Process Model and Notation',
  GDPR: 'Regolamento generale sulla protezione dei dati',
  DPO: 'Data Protection Officer',
  WebGIS: 'Sistema informativo geografico sul web',
  WEBGIS: 'Sistema informativo geografico sul web',
  GIS: 'Geographic Information System (sistema informativo geografico)',
  SPOC: 'Single Point of Contact (punto di contatto unico)',
  UAT: 'User Acceptance Test (collaudo con gli utenti)',
  MEV: 'Manutenzione Evolutiva',
  MAC: 'Manutenzione Correttiva',
  MAD: 'Manutenzione Adeguativa',
  SVI: 'Sviluppo software',
  'SPID/CIE': 'Identità digitale (SPID o Carta d\'Identità Elettronica)',
};

// Ricerca delle voci scritte in minuscolo/maiuscolo misto (PagoPA, AppIO, WebGIS) nel testo
const MIXED = Object.keys(GLOSSARIO_PA).filter((k) => /[a-z]/.test(k));

module.exports = { GLOSSARIO_PA, MIXED };
